### ISSUE TITLE
[QUESTION] 페이지의 라우트를 이렇게 하는 것이 어떨까요?

### ISSUE THREAD

**Issue by unsnruu** [numble-jjan/jjan-front-renewal#102]
## Description
#100 을 진행하면서 페이지의 라우트를 자세히 구성할 필요가 있다고 생각이 들었습니다.
그래서 아래와 같이 페이지의 라우트를 구성할 것을 제안드립니다.

## Proposal
- 스플래쉬 : splash
- 랜딩 : landing
- 회원가입 : auth/signup
- 로그인 : auth/signin
- 회원가입 완료 :  auth/signup-complete
- 프로필 : profile/:username
- 프로필 설정 : setting/profile
- 활동 지역 검색 : setting/location/search?SOMETHING
- 활동 지역 범위 설정 setting/location
- 키워드 설정 - 좋아하는 술 : setting/keyword/alcohol
- 키워드 설정 - 좋아하는 분위기 : setting/keyword/mood
- 로그아웃 완료 : auth/signout-complete
- 게시판 - 푸념 : post/vent-out
- 게시판 - 술메이트 : post/soolmate
- 게시글 상세페이지 : post/:postId
- 글쓰기 : post/write
- 글 수정: post/edit/:postId
- 커뮤니티 활동 - 내 게시판 : activity/post/:username
- 커뮤니티 활동 - 남긴 댓글: activity/comment/:username
- 댓글 수정 : comment/edit/:postId

**Comment by gomgun-lab** [comment]
노션에 문서화 시킨 후 이슈 닫겠습니다 ~
