### ISSUE TITLE
[QUESTION] FlexItem에 정렬하는 기능을 추가해야할까요?

### ISSUE THREAD

**Issue by unsnruu** [numble-jjan/jjan-front-renewal#107]
## Description
현재 Flex와 관련된 코어 컴포넌트에는 두 종류가 있습니다.
`Flexbox`의 경우에는 `justify-content` 외의 정렬과 관련된 스타일링을 담당하고 있습니다.
`FlexItem`의 경우에는 FlexBox의 자식으로 사용되어 `flex-grow, flex-shrink`와 같은 flex 속성을 담당합니다.

그런데 FlexItem의 내부에 있는 컴포넌트 혹은 문자열 등을 정렬할 필요가 느끼면 어떻게 해야할까요?

## Proposal
- `<Flexbox><FlexItem></Flexbox></FlexItem></Flexbox>`와 같은 형식으로 사용
- `FlexItem`에도 justify-content와 같은 정렬 속성을 추가

**Comment by gomgun-lab** [comment]
FlexItem이 Flexbox의 속성을 가져와서 사용하는 것일까요? 아니면 justify-content와 같은 개별 속성만 적용시키나요?

**Comment by unsnruu** [comment]
저는 개별 속성을 적용하는 쪽으로 생각했는데 
방금 주신 의견대로 FlexItem이 Flexbox를 확장해서 사용하는 방식으로 사용하게 될 것 같습니다.

다만 그렇게 될 경우에는 FlexItem과 Flexbox를 구분짓는게 큰 의미가 있을까 싶습니다!

**Comment by gomgun-lab** [comment]
이 이슈에 계속 구체적인 구현 방법을 찾은 뒤 적용 여부를 결정하면 좋겠습니다.

**Comment by unsnruu** [comment]
mixin 기법등을 사용해서 구현하는 방법도 좋을 것 같습니다.
자세한 구현 방법은 추후에 다른 라이브러리들을 참고하여 남기도록 하겠습니다.

현재로서는 대규모의 리팩토링을 거쳐야 할 것 같아서
일단 보류하기로 결정하였습니다.
