### ISSUE TITLE
fix : svg를 component화 시키기

### ISSUE THREAD

**Issue by unsnruu** [numble-jjan/jjan-front-renewal#7]
svg 이미지가 깨지는 문제가 발생하고 있습니다.
따라서 `img` 태그를 통해서 불러오는 방식이 아니라
svg를 컴포넌트화 하여 사용할 수 있게끔 수정할 예정입니다.

---
참고
https://velog.io/@juno7803/React-React%EC%97%90%EC%84%9C-SVG-%ED%99%9C%EC%9A%A9%ED%95%98%EA%B8%B0

**Comment by unsnruu** [comment]
https://velog.io/@alsxmqkqh23/React-SVG-React-Component%EB%A1%9C-%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0feat.-TypeScript-Vite

**Comment by unsnruu** [comment]
https://www.npmjs.com/package/vite-plugin-svgr

**Comment by gomgun-lab** [comment]
## 플러그인 설치

`npm i vite-plugin-svgr`

## ts 설정
#### ts.config.ts
```ts 
"include": ["src", "custom.d.ts"],
```

#### custom.d.ts
```ts
declare module '*.svg' {
  import React = require('react');
  export const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>;
  const src: string;
  export default src;
}
```
## vite 설정
#### vite.config.ts
```ts
import svgr from 'vite-plugin-svgr';

## add plugin
plugins: [svgr()]
```

## storybook 설정
#### main.cjs
```ts
const svgrPlugin = require("vite-plugin-svgr");

## add plugin
config.plugins = [...config.plugins, svgrPlugin({})]
```
