### ISSUE TITLE
[QUESTION] FlexItem 컴포넌트를 제작하면 어떨까요

### ISSUE THREAD

**Issue by unsnruu** [numble-jjan/jjan-front-renewal#90]
## Description
현재 존재하는 `FlexBox` 컴포넌트와의 시너지를 위해 
`FlexItem` 컴포넌트를 제작하면 어떨까 제안해 봅니다.

### 기능 설명
FlexItem의 경우 'flex'와 관련된 속성(flex-grow, flex-shrink 등)을
FlexBox 내부에서 제어할 수 있는 컴포넌트 입니다.

### 사용법
`FlexItem`의 경우 다음과 같은 형태로 사용되면 좋을 것 같습니다

```html
<FlexBox>
  <FlexItem>
    <Text>Item 0</Text>
  </FlexItem>
  <FlexItem flex="1">
    <Text>Item 1</Text>
  </FlexItem>
  <FlexItem flex="2">
    <Text>Item 2</Text>
  </FlexItem>
  <FlexItem flex="3">
    <Text>Item 3</Text>
  </FlexItem>
</FlexBox>
```

**Comment by gomgun-lab** [comment]
좋습니다 ~
