### ISSUE TITLE
[QUESTION] asset 파일 관리 방법 제안

### ISSUE THREAD

**Issue by gomgun-lab** [numble-jjan/jjan-front-renewal#99]
## Description

현재 프로젝트의 정적 asset 파일을 패키지로 배포하면 관리하기 편할 것 같습니다.

## Proposal

https://github.com/daangn/karrot-ui-icon/tree/main

**Comment by unsnruu** [comment]
특히 아이콘의 관리를 패키지로 하면 정말 좋을 것 같습니다
